# This is a basic workflow that is manually triggered

name: lotus

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    strategy:
      matrix:
        on: [ubuntu-latest,macos-latest,windows-latest]
        arch: [amd64, arm64]
        targetos: [windows, darwin, linux]
    runs-on: ${{ matrix.on }}
    name: baby ${{ matrix.arch }} for ${{ matrix.targetos }} built on ${{ matrix.on }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          go mod download
          go build ./...

      - uses: actions/upload-artifact@v2
        with:
          name: babyd ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/babyd/babyd
